version: "3.9"

services:
  api:
    build: backend                # <-- path relative to docker-compose.yml
    container_name: fastapi_app
    ports:
      - "8000:8000"                 # maps host:container
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/smartnotes"
      SECRET_KEY: "mysecretjwtkey"  # better: use .env for secrets
      ACCESS_TOKEN_EXPIRE_MINUTES: "60"
    depends_on:
      - db
    volumes:
      - ./backend:/app               # optional: mount source for live code changes
    restart: unless-stopped

  db:
    image: postgres
    container_name: smartnotes_db
    environment:
      POSTGRES_USER: chanchal
      POSTGRES_PASSWORD: ramu123
      POSTGRES_DB: smartnotes
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
